### ISSUE TITLE
Recommenders

### ISSUE THREAD

**Issue by delucas** [SuperHyperMegaRed/jrpg#2]
El directorio `.recommenders` no debería estar en el repositorio. Es necesario que lo agreguen al archivo `.gitignore` y que lo eliminen del repositorio.

Quizás [esto pueda ayudarlos](http://stackoverflow.com/a/1143800).

**Comment by mati13490** [comment]
Listo Lucas, ya se borro el directorio y se agrego al archivo .gitignore
